-- ============================================
-- PHASE 4: DATABASE CREATION
-- PDB Name: Mon_27119_Olivier_DigitalID_db
-- Admin User: olivier_admin
-- Password: Olivier
-- ============================================

-- 1. CREATE PLUGGABLE DATABASE WITH YOUR FILE PATHS
CREATE PLUGGABLE DATABASE Mon_27119_Olivier_DigitalID_db
ADMIN USER olivier_admin IDENTIFIED BY Olivier
FILE_NAME_CONVERT=('C:\ORACLE_INSTALL\ORADATA\ORCL\PDBSEED',
                   'C:\ORACLE_INSTALL\ORADATA\ORCL\Mon_27119_Olivier_DigitalID_db');

-- 2. OPEN THE PDB
ALTER PLUGGABLE DATABASE Mon_27119_Olivier_DigitalID_db OPEN;

-- 3. SWITCH TO THE NEW PDB
ALTER SESSION SET CONTAINER = Mon_27119_Olivier_DigitalID_db;

-- 4. CREATE TABLESPACES
CREATE TABLESPACE tbs_data 
DATAFILE 'C:\ORACLE_INSTALL\ORADATA\ORCL\Mon_27119_Olivier_DigitalID_db\tbs_data.dbf' 
SIZE 200M AUTOEXTEND ON NEXT 50M MAXSIZE 1G;

CREATE TABLESPACE tbs_idx 
DATAFILE 'C:\ORACLE_INSTALL\ORADATA\ORCL\Mon_27119_Olivier_DigitalID_db\tbs_idx.dbf' 
SIZE 100M AUTOEXTEND ON NEXT 20M MAXSIZE 500M;

CREATE TEMPORARY TABLESPACE temp_digital 
TEMPFILE 'C:\ORACLE_INSTALL\ORADATA\ORCL\Mon_27119_Olivier_DigitalID_db\temp_digital.dbf' 
SIZE 100M AUTOEXTEND ON;

-- 5. CREATE PROJECT USER
CREATE USER digital_id_user IDENTIFIED BY Olivier2025;

-- 6. GRANT PRIVILEGES (YOUR METHOD)
GRANT ALL PRIVILEGES TO digital_id_user;
GRANT UNLIMITED TABLESPACE TO digital_id_user;

-- 7. ENABLE ARCHIVELOG (for auditing)
ALTER DATABASE ARCHIVELOG;

-- 8. SET MEMORY PARAMETERS (optional)
ALTER SYSTEM SET SGA_TARGET=512M SCOPE=SPFILE;
ALTER SYSTEM SET PGA_AGGREGATE_TARGET=256M SCOPE=SPFILE;

COMMIT;

