-- ============================================
-- PHASE 5: DATA VALIDATION QUERIES
-- Simple checks to ensure database is set up correctly
-- ============================================

-- 1. SHOW ALL TABLES AND ROW COUNTS
SELECT 'CITIZENS' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM CITIZENS UNION ALL
SELECT 'GOVERNMENT_AGENCIES', COUNT(*) FROM GOVERNMENT_AGENCIES UNION ALL
SELECT 'AGENCY_EMPLOYEES', COUNT(*) FROM AGENCY_EMPLOYEES UNION ALL
SELECT 'ACCESS_PERMISSIONS', COUNT(*) FROM ACCESS_PERMISSIONS UNION ALL
SELECT 'ACCESS_AUDIT_LOG', COUNT(*) FROM ACCESS_AUDIT_LOG UNION ALL
SELECT 'PRIVACY_VIOLATIONS', COUNT(*) FROM PRIVACY_VIOLATIONS;

-- 2. SHOW FIRST 5 CITIZENS
SELECT 'FIRST 5 CITIZENS:' AS TEST_RESULT FROM DUAL;
SELECT CITIZEN_ID, FULL_NAME, DISTRICT, STATUS FROM CITIZENS WHERE ROWNUM <= 5;

-- 3. SHOW ALL GOVERNMENT AGENCIES
SELECT 'ALL GOVERNMENT AGENCIES:' AS TEST_RESULT FROM DUAL;
SELECT AGENCY_ID, AGENCY_NAME, AGENCY_TYPE FROM GOVERNMENT_AGENCIES ORDER BY AGENCY_NAME;

-- 4. SHOW EMPLOYEES WITH THEIR AGENCIES
SELECT 'EMPLOYEES AND THEIR AGENCIES:' AS TEST_RESULT FROM DUAL;
SELECT 
    AGENCY_EMPLOYEES.EMP_NAME,
    AGENCY_EMPLOYEES.POSITION,
    GOVERNMENT_AGENCIES.AGENCY_NAME
FROM AGENCY_EMPLOYEES
JOIN GOVERNMENT_AGENCIES ON AGENCY_EMPLOYEES.AGENCY_ID = GOVERNMENT_AGENCIES.AGENCY_ID
WHERE ROWNUM <= 5;

-- 5. SHOW ACCESS PERMISSIONS
SELECT 'ACCESS PERMISSIONS:' AS TEST_RESULT FROM DUAL;
SELECT 
    GOVERNMENT_AGENCIES.AGENCY_NAME,
    ACCESS_PERMISSIONS.DATA_CATEGORY,
    ACCESS_PERMISSIONS.PURPOSE,
    ACCESS_PERMISSIONS.EXPIRY_DATE
FROM ACCESS_PERMISSIONS
JOIN GOVERNMENT_AGENCIES ON ACCESS_PERMISSIONS.AGENCY_ID = GOVERNMENT_AGENCIES.AGENCY_ID
ORDER BY GOVERNMENT_AGENCIES.AGENCY_NAME;

-- 6. CHECK THAT AUDIT TABLES ARE EMPTY
SELECT 'AUDIT TABLES SHOULD BE EMPTY:' AS TEST_RESULT FROM DUAL;
SELECT 'ACCESS_AUDIT_LOG' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM ACCESS_AUDIT_LOG UNION ALL
SELECT 'PRIVACY_VIOLATIONS', COUNT(*) FROM PRIVACY_VIOLATIONS;

-- 7. CHECK FOR ANY ERRORS IN DATA
SELECT 'DATA QUALITY CHECKS:' AS TEST_RESULT FROM DUAL;
SELECT 'Citizens with missing names:' AS CHECK_NAME, COUNT(*) FROM CITIZENS WHERE FULL_NAME IS NULL UNION ALL
SELECT 'Employees without usernames:', COUNT(*) FROM AGENCY_EMPLOYEES WHERE USERNAME IS NULL UNION ALL
SELECT 'Permissions without expiry dates:', COUNT(*) FROM ACCESS_PERMISSIONS WHERE EXPIRY_DATE IS NULL;

-- 8. VERIFY UNIQUE PHONE NUMBERS
SELECT 'Checking for duplicate phone numbers:' AS TEST_RESULT FROM DUAL;
SELECT PHONE, COUNT(*) AS DUPLICATE_COUNT 
FROM CITIZENS 
GROUP BY PHONE 
HAVING COUNT(*) > 1;
