-- ============================================
-- PHASE 5: TEST QUERIES
-- Simple queries to test database functionality
-- ============================================

-- 1. BASIC RETRIEVAL (SELECT * with conditions)
SELECT 'TEST 1: Citizens in Gasabo district' AS TEST_NAME FROM DUAL;
SELECT CITIZEN_ID, FULL_NAME, PHONE, EMAIL, STATUS
FROM CITIZENS
WHERE DISTRICT = 'Gasabo'
AND ROWNUM <= 10;

-- 2. MULTI-TABLE JOIN (3 tables joined)
SELECT 'TEST 2: Employees with their agency details' AS TEST_NAME FROM DUAL;
SELECT 
    AGENCY_EMPLOYEES.EMP_NAME AS EMPLOYEE_NAME,
    AGENCY_EMPLOYEES.POSITION AS JOB_TITLE,
    GOVERNMENT_AGENCIES.AGENCY_NAME AS AGENCY,
    GOVERNMENT_AGENCIES.AGENCY_TYPE AS AGENCY_TYPE
FROM AGENCY_EMPLOYEES
JOIN GOVERNMENT_AGENCIES ON AGENCY_EMPLOYEES.AGENCY_ID = GOVERNMENT_AGENCIES.AGENCY_ID
WHERE ROWNUM <= 10
ORDER BY GOVERNMENT_AGENCIES.AGENCY_NAME, AGENCY_EMPLOYEES.EMP_NAME;

-- 3. AGGREGATION WITH GROUP BY
SELECT 'TEST 3: Count of citizens per district' AS TEST_NAME FROM DUAL;
SELECT DISTRICT, COUNT(*) AS NUMBER_OF_CITIZENS
FROM CITIZENS
GROUP BY DISTRICT
ORDER BY NUMBER_OF_CITIZENS DESC;

-- 4. SUBQUERY EXAMPLE
SELECT 'TEST 4: Citizens with specific criteria' AS TEST_NAME FROM DUAL;
SELECT FULL_NAME, PHONE, DISTRICT, STATUS
FROM CITIZENS
WHERE CITIZEN_ID IN (
    SELECT CITIZEN_ID 
    FROM CITIZENS 
    WHERE DISTRICT = 'Gasabo' 
    AND STATUS = 'ACTIVE'
)
AND ROWNUM <= 5;

-- 5. CHECK PERMISSIONS BY CATEGORY
SELECT 'TEST 5: Financial data access permissions' AS TEST_NAME FROM DUAL;
SELECT 
    GOVERNMENT_AGENCIES.AGENCY_NAME,
    ACCESS_PERMISSIONS.PURPOSE,
    ACCESS_PERMISSIONS.EXPIRY_DATE
FROM ACCESS_PERMISSIONS
JOIN GOVERNMENT_AGENCIES ON ACCESS_PERMISSIONS.AGENCY_ID = GOVERNMENT_AGENCIES.AGENCY_ID
WHERE ACCESS_PERMISSIONS.DATA_CATEGORY = 'FINANCIAL'
ORDER BY GOVERNMENT_AGENCIES.AGENCY_NAME;

-- 6. EMPLOYEES PER AGENCY COUNT
SELECT 'TEST 6: Number of employees in each agency' AS TEST_NAME FROM DUAL;
SELECT 
    GOVERNMENT_AGENCIES.AGENCY_NAME,
    COUNT(AGENCY_EMPLOYEES.EMPLOYEE_ID) AS EMPLOYEE_COUNT
FROM GOVERNMENT_AGENCIES
LEFT JOIN AGENCY_EMPLOYEES ON GOVERNMENT_AGENCIES.AGENCY_ID = AGENCY_EMPLOYEES.AGENCY_ID
GROUP BY GOVERNMENT_AGENCIES.AGENCY_NAME
ORDER BY EMPLOYEE_COUNT DESC;

-- 7. CHECK EXPIRING PERMISSIONS
SELECT 'TEST 7: Permissions expiring soon' AS TEST_NAME FROM DUAL;
SELECT 
    GOVERNMENT_AGENCIES.AGENCY_NAME,
    ACCESS_PERMISSIONS.DATA_CATEGORY,
    ACCESS_PERMISSIONS.EXPIRY_DATE,
    CASE 
        WHEN ACCESS_PERMISSIONS.EXPIRY_DATE < SYSDATE THEN 'EXPIRED'
        WHEN ACCESS_PERMISSIONS.EXPIRY_DATE < SYSDATE + 30 THEN 'EXPIRING IN 30 DAYS'
        ELSE 'VALID' 
    END AS STATUS
FROM ACCESS_PERMISSIONS
JOIN GOVERNMENT_AGENCIES ON ACCESS_PERMISSIONS.AGENCY_ID = GOVERNMENT_AGENCIES.AGENCY_ID
WHERE ACCESS_PERMISSIONS.EXPIRY_DATE < SYSDATE + 90
ORDER BY ACCESS_PERMISSIONS.EXPIRY_DATE;

-- 8. SIMPLE DATE FUNCTION TEST
SELECT 'TEST 8: Citizen age calculation' AS TEST_NAME FROM DUAL;
SELECT 
    FULL_NAME,
    DOB AS DATE_OF_BIRTH,
    TRUNC(MONTHS_BETWEEN(SYSDATE, DOB)/12) AS AGE
FROM CITIZENS
WHERE ROWNUM <= 5
AND DOB IS NOT NULL;
